- hosts: localhost
  become: true
  become_user: mviera
  become_method: sudo
  vars:
    home: /home/mviera
    user: mviera

#  pre_tasks:
#    - name: update repositories
#      apt: update_cache=yes
#      changed_when: False

  tasks:
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/repositories.yml
    - include_tasks: tasks/dotfiles.yml

# TODO: Adds this config to a recipe.
#sudo apt install pinentry-tty
#sudo update-alternatives --config pinentry
