- name: Clone github repositories
  git: repo={{ item.git }} dest={{ home }}/{{ item.path }}
  with_items:
    -
      git: git@github.com:mviera/dotfiles.git
      path: src/personal/dotfiles
  become_user: mviera
